---
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(deps): "

  # Maintain dependencies for npm
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-major]
    commit-message:
      prefix: "chore: "
    open-pull-requests-limit: 5
