name: Version Package

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Get github app token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: gh-app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout Repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4.5.4
        with:
          token: ${{ steps.gh-app-token.outputs.token }}
          fetch-depth: 0
          persist-credentials: false

      - name: Prepare pre-requisites
        uses: ./.github/actions/prepare
        with:
          token: ${{ steps.gh-app-token.outputs.token }}

      - name: Create Release Pull Request
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          commitMode: "github-api"
          version: pnpm ci:version
          title: "ci: update the version packages"
        env:
          GITHUB_TOKEN: ${{ steps.gh-app-token.outputs.token }}

      - name: Update the lock file
        run: pnpm install --lockfile-only
        shell: bash

      - name: Set up upstream branch
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/changeset-release/main; then
            git push --set-upstream origin changeset-release/main
          else
            echo "Skipping because the branch changeset-release/main does not exist..."
          fi
        shell: bash

      - name: Commit pnpm-lock.yaml file changes
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ steps.gh-app-token.outputs.token }}
          sign-commits: true
          commit-message: "🤖 chore: Update the pnpm-lock.yaml file"
          title: "chore: 🤖 [Automated PR] Update the pnpm-lock.yaml file"
          body: |
            This PR updates the pnpm-lock.yaml file
